nickname = "Test"
STR = 9
DEX = 9
CON = 17
INT = 11
WIS = 10
CHA = 12
BAB = 1
AC = 12
HP = 10
HD = 0
Weapondie = 4
Initiative = 1
Level = 1
Class = "Fighter"
Armor = "Leather Armor"
Weapon = "dagger"
area = "City"
room = "Inn"
position = "16"
